---
- hosts: all
  become: true
  tasks:
    - name: Upgrade the OS, autoremove & autoclean
      ansible.builtin.apt:
        pkg: "*"
        state: latest # noqa package-latest
        autoremove: true
        autoclean: true
        update_cache: true
        cache_valid_time: 3600
    - name: Set sysctl for higher network throughput
      ansible.posix.sysctl:
        name: '{{ item.name }}'
        value: '{{ item.value }}'
        state: present
      loop:
        - name: net.ipv4.neigh.default.gc_thresh1
          value: '8192'
        - name: net.ipv4.neigh.default.gc_thresh2
          value: '12228'
        - name: net.ipv4.neigh.default.gc_thresh3
          value: '24456'
        - name: net.ipv4.neigh.default.gc_stale_time
          value: '60'
        - name: net.ipv4.neigh.default.gc_interval
          value: '30'
        - name: net.ipv4.neigh.default.base_reachable_time_ms
          value: '30000'
        - name: net.ipv4.ip_local_port_range
          value: '1024 65535'
        - name: net.ipv4.tcp_tw_reuse
          value: '1'
        - name: net.ipv4.tcp_fin_timeout
          value: '15'
        - name: net.core.somaxconn
          value: '4096'
        - name: net.core.netdev_max_backlog
          value: '4096'
        - name: net.core.rmem_max
          value: 16777216
        - name: net.core.wmem_max
          value: 16777216
        - name: net.ipv4.tcp_max_syn_backlog
          value: '20480'
        - name: net.ipv4.tcp_max_tw_buckets
          value: '400000'
        - name: net.ipv4.tcp_syn_retries
          value: '2'
        - name: net.ipv4.tcp_synack_retries
          value: '2'
        - name: net.netfilter.nf_conntrack_max
          value: '262144'
        - name: net.netfilter.nf_conntrack_tcp_timeout_established
          value: '86400'
  roles:
    - role: geerlingguy.pip
      tags: ["docker"]
    - role: geerlingguy.docker
      tags: ["docker"]
