---
- hosts: all
  become: true
  tasks:
    - name: Upgrade the OS, autoremove & autoclean
      ansible.builtin.apt:
        pkg: "*"
        state: latest # noqa package-latest
        autoremove: true
        autoclean: true
        update_cache: true
        cache_valid_time: 3600
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
